# Generated by Django 3.2 on 2021-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, default='https://marlenalmurtagh.files.wordpress.com/2014/11/movie-template1.jpg', max_length=200, null=True),
        ),
    ]
